name: Rust

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.REX_DEPLOY_KEY }}
      - name: Add wasm target
        run: cargo --version
      - name: Build
        run: cargo build --verbose
      - name: Add wasm target
        run: rustup target add wasm32-unknown-unknown
      - name: Build wasm
        run: cargo build --package ouroboros-vm-prelude --target wasm32-unknown-unknown --no-default-features
      - name: Run tests
        run: cargo test --verbose
      - name: Run clippy
        run: cargo clippy --all-features
