use ouroboros::alias::Alias;
use ouroboros::field::{Fields, NamedField, NamedFields, UnnamedField, UnnamedFields};
use ouroboros::product::{Array, Func, Record, RecordDocs, RecordFieldDocs, Tuple};
use ouroboros::ptr::Ptr;
use ouroboros::sum::{Enum, EnumVariant, Fallible, Optional, Union, UnionVariant};
use ouroboros::symbolic::Symbolic;
use ouroboros::type_info::Type as OuroborosType;
use rex::type_system::types::{ADT, ADTVariant, Type as RexType};
use std::{
    collections::{BTreeMap, HashMap},
    sync::Arc,
};

// Note: We cannot use From/Into here as these only work if the types
// they are implemented on are defined in the same crate

pub fn ouroboros_to_rex(our_type: &OuroborosType) -> Arc<RexType> {
    match our_type {
        OuroborosType::Unit => Arc::new(RexType::Tuple(vec![])),
        OuroborosType::Bool => Arc::new(RexType::Bool),
        OuroborosType::I8 => Arc::new(RexType::Int),
        OuroborosType::I16 => Arc::new(RexType::Int),
        OuroborosType::I32 => Arc::new(RexType::Int),
        OuroborosType::I64 => Arc::new(RexType::Int),
        OuroborosType::I128 => panic!("Unsupported ouroboros type: I128"),
        OuroborosType::U8 => Arc::new(RexType::Uint),
        OuroborosType::U16 => Arc::new(RexType::Uint),
        OuroborosType::U32 => Arc::new(RexType::Uint),
        OuroborosType::U64 => Arc::new(RexType::Uint),
        OuroborosType::U128 => panic!("Unsupported ouroboros type: U128"),
        OuroborosType::F32 => Arc::new(RexType::Float),
        OuroborosType::F64 => Arc::new(RexType::Float),
        OuroborosType::String => Arc::new(RexType::String),
        OuroborosType::Array(a) => Arc::new(RexType::List(ouroboros_to_rex(&a.t))),
        OuroborosType::Record(r) => {
            let t_docs: Option<BTreeMap<String, String>> = match &r.doc {
                Some(rdocs) => match &rdocs.fields {
                    Some(RecordFieldDocs::Named(named)) => {
                        if named.len() > 0 {
                            Some(BTreeMap::from_iter(named.clone().into_iter()))
                        } else {
                            None
                        }
                    }
                    Some(RecordFieldDocs::Unnamed(_)) => None,
                    None => None,
                },
                None => None,
            };

            Arc::new(RexType::ADT(ADT {
                name: r.n.clone(),
                variants: vec![ADTVariant {
                    name: r.n.clone(),
                    t: Some(fields_to_rex(&r.fields)),
                    docs: None,
                    t_docs: t_docs,
                }],
                docs: None, // Not generated by #[derive(TypeInfo)]
            }))
        }
        OuroborosType::Tuple(tuple) => unnamed_fields_to_rex(&tuple.fields),
        OuroborosType::Func(func) => Arc::new(RexType::Arrow(
            ouroboros_to_rex(&*func.a),
            ouroboros_to_rex(&*func.b),
        )),
        OuroborosType::Enum(e) => {
            Arc::new(RexType::ADT(ADT {
                name: e.n.clone(),
                variants: e
                    .variants
                    .iter()
                    .map(|v| ADTVariant {
                        name: v.n.clone(),
                        t: None,
                        docs: None,
                        t_docs: None,
                    })
                    .collect::<Vec<_>>(),
                docs: None, // Not generated by #[derive(TypeInfo)]
            }))
        }
        OuroborosType::Fallible(f) => Arc::new(RexType::Result(
            ouroboros_to_rex(&f.ok),
            ouroboros_to_rex(&f.err),
        )),
        OuroborosType::Optional(o) => Arc::new(RexType::Option(ouroboros_to_rex(&o.t))),
        OuroborosType::Union(u) => Arc::new(RexType::ADT(ADT {
            name: u.n.clone(),
            variants: u
                .variants
                .iter()
                .map(|v| ADTVariant {
                    name: v.n.clone(),
                    t: match &v.fields {
                        Some(Fields::Named(fields)) => Some(named_fields_to_rex(fields)),
                        Some(Fields::Unnamed(fields)) => match fields.fields.len() {
                            0 => None,
                            1 => Some(ouroboros_to_rex(&fields.fields[0].t)),
                            _ => Some(unnamed_fields_to_rex(fields)),
                        },
                        None => None,
                    },
                    docs: None,
                    t_docs: None,
                })
                .collect(),
            docs: None,
        })),
        OuroborosType::Ptr(ptr) => Arc::new(RexType::ADT(ADT {
            name: "Ptr".to_string(),
            docs: None,
            variants: vec![ADTVariant {
                name: "Ptr".to_string(),
                t: Some(ouroboros_to_rex(&*ptr.t)),
                docs: None,
                t_docs: None,
            }],
        })),
        OuroborosType::Symbolic(symbolic) => Arc::new(RexType::ADT(ADT {
            name: symbolic.n.to_string(),
            docs: symbolic.doc.as_ref().map(|d| d.to_string()),
            variants: vec![ADTVariant {
                name: symbolic.n.clone(),
                t: None,
                docs: None,
                t_docs: None,
            }],
        })),
        OuroborosType::Generic(_) => panic!("Unsupported ouroboros type: Generic"),
        OuroborosType::Alias(alias) => Arc::new(RexType::ADT(ADT {
            name: alias.n.clone(),
            variants: vec![ADTVariant {
                name: alias.n.clone(),
                t: Some(ouroboros_to_rex(&*alias.t)),
                docs: None,
                t_docs: None,
            }],
            docs: None,
        })),
    }
}

fn fields_to_rex(fields: &Fields) -> Arc<RexType> {
    match fields {
        Fields::Named(named) => named_fields_to_rex(named),
        Fields::Unnamed(unnamed) => unnamed_fields_to_rex(unnamed),
    }
}

fn named_fields_to_rex(fields: &NamedFields) -> Arc<RexType> {
    let mut entries: BTreeMap<String, Arc<RexType>> = BTreeMap::new();
    for field in fields.fields.iter() {
        entries.insert(field.n.clone(), ouroboros_to_rex(&field.t));
    }
    Arc::new(RexType::Dict(entries))
}

fn unnamed_fields_to_rex(fields: &UnnamedFields) -> Arc<RexType> {
    let mut rex_types: Vec<Arc<RexType>> = Vec::new();
    for field in fields.iter() {
        rex_types.push(ouroboros_to_rex(&field.t));
    }
    Arc::new(RexType::Tuple(rex_types))
}

fn rex_to_fields(rex_type: &RexType) -> Fields {
    match rex_type {
        RexType::Tuple(rex_types) => {
            let mut our_fields: Vec<UnnamedField> = Vec::new();
            for t in rex_types.iter() {
                our_fields.push(UnnamedField {
                    t: rex_to_ouroboros(t),
                });
            }
            Fields::Unnamed(UnnamedFields { fields: our_fields })
        }
        RexType::Dict(entries) => {
            let mut our_fields: Vec<NamedField> = Vec::new();
            for (k, t) in entries.iter() {
                our_fields.push(NamedField {
                    n: k.clone(),
                    t: rex_to_ouroboros(t),
                });
            }
            Fields::Named(NamedFields { fields: our_fields })
        }
        _ => Fields::Unnamed(UnnamedFields {
            fields: vec![UnnamedField {
                t: rex_to_ouroboros(rex_type),
            }],
        }),
    }
}

pub fn rex_to_ouroboros(rex_type: &RexType) -> OuroborosType {
    match rex_type {
        RexType::UnresolvedVar(_) => panic!("Unsupported Rex type: UnresolvedVar"),
        RexType::Var(_) => panic!("Unsupported Rex type: Var"),
        RexType::ForAll(_, _, _) => panic!("Unsupported Rex type: ForAll"),
        RexType::ADT(adt) => rex_adt_to_ouroboros(adt),
        RexType::Arrow(a, b) => OuroborosType::Func(Func {
            a: Box::new(rex_to_ouroboros(a)),
            b: Box::new(rex_to_ouroboros(b)),
        }),
        RexType::Result(ok, err) => OuroborosType::Fallible(Fallible {
            ok: Box::new(rex_to_ouroboros(ok)),
            err: Box::new(rex_to_ouroboros(err)),
        }),
        RexType::Option(t) => OuroborosType::Optional(Optional {
            t: Box::new(rex_to_ouroboros(t)),
        }),
        RexType::Promise(_) => panic!("Unsupported Rex type: Promise"),
        RexType::List(t) => OuroborosType::Array(Array::new(rex_to_ouroboros(t))),
        RexType::Dict(_) => panic!("Unsupported Rex type: Dict"),
        RexType::Tuple(ts) => {
            if ts.len() == 0 {
                OuroborosType::Unit
            } else {
                OuroborosType::Tuple(Tuple {
                    fields: UnnamedFields {
                        fields: ts
                            .iter()
                            .map(|t| UnnamedField::new(rex_to_ouroboros(t)))
                            .collect(),
                    },
                })
            }
        }
        RexType::Bool => OuroborosType::Bool,
        RexType::Uint => OuroborosType::U64,
        RexType::Int => OuroborosType::I64,
        RexType::Float => OuroborosType::F64,
        RexType::String => OuroborosType::String,
        RexType::Uuid => panic!("Unsupported Rex type: Uuid"),
        RexType::DateTime => panic!("Unsupported Rex type: DateTime"),
    }
}

fn rex_adt_to_ouroboros(adt: &ADT) -> OuroborosType {
    if adt.variants.len() == 1 {
        match adt.variants[0].t.as_deref() {
            // ADT with a single variant whose type is a dict -> Record w/named fields
            Some(RexType::Dict(entries)) => {
                return rex_record_to_ouroboros(&adt.name, &adt.variants[0].t_docs, entries);
            }
            // ADT with a single variant whose type is a tuple -> Record w/unnamed fields
            Some(RexType::Tuple(entries)) => {
                return OuroborosType::Record(Record {
                    doc: None,
                    n: adt.name.clone(),
                    fields: Fields::Unnamed(UnnamedFields {
                        fields: entries
                            .iter()
                            .map(|e| UnnamedField {
                                t: rex_to_ouroboros(e),
                            })
                            .collect(),
                    }),
                });
            }
            // ADT with a single variant of another type -> Alias
            Some(t) => {
                if adt.name == "Ptr" && adt.variants[0].name == "Ptr" {
                    return OuroborosType::Ptr(Ptr {
                        t: Box::new(rex_to_ouroboros(t)),
                    });
                }

                return OuroborosType::Alias(Alias {
                    n: adt.name.clone(),
                    t: Box::new(rex_to_ouroboros(t)),
                });
            }
            None => {
                if adt.variants[0].name == adt.name {
                    return OuroborosType::Symbolic(Symbolic {
                        n: adt.name.clone(),
                        doc: adt.docs.clone(),
                    });
                }
            }
        }
    }

    // ADT where no member carries any data value -> Enum
    if adt.variants.iter().all(|v| v.t.is_none()) {
        return rex_enum_to_ouroboros(&adt.name, &adt.variants);
    }

    // General ADT
    let mut our_variants: Vec<UnionVariant> = Vec::new();
    for rex_variant in adt.variants.iter() {
        let fields: Option<Fields> = match &rex_variant.t {
            Some(rex_fields) => Some(rex_to_fields(rex_fields)),
            None => None,
        };
        our_variants.push(UnionVariant {
            n: rex_variant.name.clone(),
            fields,
        })
    }
    let union_ = Union {
        doc: None,
        n: adt.name.clone(),
        variants: our_variants,
    };
    OuroborosType::Union(union_)
}

fn rex_record_to_ouroboros(
    name: &str,
    t_docs: &Option<BTreeMap<String, String>>,
    entries: &BTreeMap<String, Arc<RexType>>,
) -> OuroborosType {
    // Match behaviour of #[derive(TypeInfo)] - use empty hashmap for field docs if
    // there are no actual docs present
    let hm: HashMap<String, String> = match t_docs {
        Some(entries) => HashMap::from_iter(entries.clone().into_iter()),
        None => HashMap::new(),
    };
    let doc: Option<RecordDocs> = Some(RecordDocs {
        record: None,
        fields: Some(RecordFieldDocs::Named(hm)),
    });

    let fields = entries
        .iter()
        .map(|(k, v)| NamedField {
            n: k.clone(),
            t: rex_to_ouroboros(v),
        })
        .collect::<Vec<_>>();

    return OuroborosType::Record(Record {
        doc,
        n: name.to_string(),
        fields: Fields::Named(NamedFields { fields }),
    });
}

fn rex_enum_to_ouroboros(name: &str, variants: &[ADTVariant]) -> OuroborosType {
    OuroborosType::Enum(Enum {
        doc: None,
        n: name.to_string(),
        variants: variants
            .iter()
            .map(|v| EnumVariant {
                n: v.name.clone(),
                v: None,
            })
            .collect(),
    })
}

#[cfg(test)]
#[cfg(test)]
pub mod test {
    #![allow(dead_code)]
    use super::*;
    use ouroboros::{ptr::Ptr as OuroborosPtr, type_info::TypeInfo};
    use ouroboros_proc_macro::*;
    use rex::{Rex, type_system::types::ToType};
    // use rex_type_system::types as rex;

    #[test]
    fn test_unit() {
        assert_eq!(
            *ouroboros_to_rex(&OuroborosType::Unit),
            RexType::Tuple(vec![])
        );
        assert_eq!(
            rex_to_ouroboros(&RexType::Tuple(vec![])),
            OuroborosType::Unit
        )
    }

    #[test]
    fn test_tuple1() {
        let our_type = OuroborosType::Tuple(Tuple {
            fields: UnnamedFields {
                fields: vec![UnnamedField {
                    t: OuroborosType::U64,
                }],
            },
        });
        let rex_type = ouroboros_to_rex(&our_type);
        assert_eq!(*rex_type, RexType::Tuple(vec![Arc::new(RexType::Uint)]));
        assert_eq!(rex_to_ouroboros(&rex_type), our_type);
    }

    #[test]
    fn test_tuple2() {
        let our_type = OuroborosType::Tuple(Tuple {
            fields: UnnamedFields {
                fields: vec![
                    UnnamedField {
                        t: OuroborosType::U64,
                    },
                    UnnamedField {
                        t: OuroborosType::String,
                    },
                ],
            },
        });
        let rex_type = ouroboros_to_rex(&our_type);
        assert_eq!(
            *rex_type,
            RexType::Tuple(vec![Arc::new(RexType::Uint), Arc::new(RexType::String)])
        );
        assert_eq!(rex_to_ouroboros(&rex_type), our_type);
    }

    #[test]
    fn test_record_named() {
        #[derive(Rex, TypeInfo)]
        struct Foo {
            /// First field
            a: u64,
            /// Second field
            b: String,
        }

        assert_eq!(*ouroboros_to_rex(&Foo::t()), Foo::to_type());
        assert_eq!(rex_to_ouroboros(&Foo::to_type()), Foo::t())
    }

    #[test]
    fn test_record_unnamed() {
        #[derive(Rex, TypeInfo)]
        pub struct Foo(pub u64, pub String);

        assert_eq!(*ouroboros_to_rex(&Foo::t()), Foo::to_type());
        assert_eq!(rex_to_ouroboros(&Foo::to_type()), Foo::t())
    }

    #[test]
    fn test_enum() {
        #[derive(Rex, TypeInfo)]
        enum Foo {
            One,
            Two,
        }

        assert_eq!(*ouroboros_to_rex(&Foo::t()), Foo::to_type());
        assert_eq!(rex_to_ouroboros(&Foo::to_type()), Foo::t());
    }

    #[test]
    fn test_enum_int() {
        mod int {
            use ouroboros_proc_macro::*;
            use rex::Rex;

            #[derive(Rex, TypeInfo)]
            pub enum Foo {
                One = 1,
                Two = 2,
                Three = 3,
            }
        }

        mod plain {
            use ouroboros_proc_macro::*;
            use rex::Rex;

            #[derive(Rex, TypeInfo)]
            pub enum Foo {
                One,
                Two,
                Three,
            }
        }

        // Rex's ADTVariant doesn't keep track of the integer values associated with enum
        // variants. So when we convert back to the ouroboros type, we'll get the same result
        // as derive(TypeInfo) would produce if there were no integer values in the enum.
        assert_eq!(*ouroboros_to_rex(&int::Foo::t()), int::Foo::to_type());
        assert_eq!(rex_to_ouroboros(&int::Foo::to_type()), plain::Foo::t());
    }

    #[test]
    fn test_union_single_field() {
        #[derive(Rex, TypeInfo)]
        enum Foo {
            One(u64),
            Two(String),
        }

        assert_eq!(*ouroboros_to_rex(&Foo::t()), Foo::to_type());
        assert_eq!(rex_to_ouroboros(&Foo::to_type()), Foo::t());
    }

    #[test]
    fn test_union_multiple_fields() {
        #[derive(Rex, TypeInfo)]
        enum Foo {
            One(u64, bool),
            Two(String, f64),
        }

        assert_eq!(*ouroboros_to_rex(&Foo::t()), Foo::to_type());
        assert_eq!(rex_to_ouroboros(&Foo::to_type()), Foo::t());
    }

    #[test]
    fn test_union_mixed() {
        #[derive(Rex, TypeInfo)]
        enum Foo {
            One,
            Two(u64),
            Three(String, f64),
        }

        assert_eq!(*ouroboros_to_rex(&Foo::t()), Foo::to_type());
        assert_eq!(rex_to_ouroboros(&Foo::to_type()), Foo::t());
    }

    #[test]
    fn test_union_named() {
        #[derive(Rex, TypeInfo)]
        enum Foo {
            One { a: u64, b: String },
            Two { a: f64, b: bool },
        }

        assert_eq!(*ouroboros_to_rex(&Foo::t()), Foo::to_type());
        assert_eq!(rex_to_ouroboros(&Foo::to_type()), Foo::t());
    }

    #[test]
    fn test_numeric_roundtrip() {
        // Rex only supports 64-bit numeric types (Uint, Int, Float). Converting from ouroboros
        // types to rex again will therefore result in only the 64-bit variants being present.
        mod different_sizes {
            use ouroboros_proc_macro::*;
            use rex::Rex;

            #[derive(Rex, TypeInfo)]
            pub struct Foo {
                pub u1: u8,
                pub u2: u16,
                pub u3: u32,
                pub u4: u64,
                pub i1: i8,
                pub i2: i16,
                pub i3: i32,
                pub i4: i64,
                pub f1: f32,
                pub f2: f64,
            }
        }

        mod all_64 {
            use ouroboros_proc_macro::*;
            use rex::Rex;

            #[derive(Rex, TypeInfo)]
            pub struct Foo {
                pub u1: u64,
                pub u2: u64,
                pub u3: u64,
                pub u4: u64,
                pub i1: i64,
                pub i2: i64,
                pub i3: i64,
                pub i4: i64,
                pub f1: f64,
                pub f2: f64,
            }
        }

        assert_eq!(
            rex_to_ouroboros(&ouroboros_to_rex(&different_sizes::Foo::t())),
            all_64::Foo::t()
        );

        assert_eq!(
            *ouroboros_to_rex(&different_sizes::Foo::t()),
            all_64::Foo::to_type()
        );
    }

    #[test]
    fn test_alias() {
        #[derive(Rex, TypeInfo)]
        pub struct Foo(u64);

        let our_type = OuroborosType::Alias(Alias {
            n: "Foo".to_string(),
            t: Box::new(OuroborosType::U64),
        });
        let rex_type = Foo::to_type();

        assert_eq!(*ouroboros_to_rex(&our_type), rex_type);
        assert_eq!(rex_to_ouroboros(&rex_type), our_type);
    }

    #[test]
    fn test_symbolic_doc() {
        #[derive(Rex, TypeInfo)]
        /// Test
        pub enum Foo {
            Foo,
        }

        let our_type = OuroborosType::Symbolic(Symbolic {
            n: "Foo".to_string(),
            doc: Some("Test".to_string()),
        });
        let rex_type = Foo::to_type();

        assert_eq!(*ouroboros_to_rex(&our_type), rex_type);
        assert_eq!(rex_to_ouroboros(&rex_type), our_type);
    }

    #[test]
    fn test_symbolic_nodoc() {
        #[derive(Rex, TypeInfo)]
        pub enum Foo {
            Foo,
        }

        let our_type = OuroborosType::Symbolic(Symbolic {
            n: "Foo".to_string(),
            doc: None,
        });
        let rex_type = Foo::to_type();

        assert_eq!(*ouroboros_to_rex(&our_type), rex_type);
        assert_eq!(rex_to_ouroboros(&rex_type), our_type);
    }

    #[test]
    fn test_ptr() {
        #[derive(Rex)]
        pub enum Ptr {
            Ptr(String),
        }

        let our_type = OuroborosType::Ptr(OuroborosPtr {
            t: Box::new(OuroborosType::String),
        });
        let rex_type = Ptr::to_type();
        assert_eq!(*ouroboros_to_rex(&our_type), rex_type);
        assert_eq!(rex_to_ouroboros(&rex_type), our_type);
    }

    #[test]
    fn test_func() {
        let our_type = OuroborosType::Func(Func {
            a: Box::new(OuroborosType::U64),
            b: Box::new(OuroborosType::String),
        });
        let rex_type = Arc::new(RexType::Arrow(
            Arc::new(RexType::Uint),
            Arc::new(RexType::String),
        ));

        assert_eq!(ouroboros_to_rex(&our_type), rex_type);
        assert_eq!(rex_to_ouroboros(&rex_type), our_type);
    }

    #[test]
    fn test_fallible() {
        #[derive(Rex, TypeInfo)]
        pub struct Foo {
            pub a: Result<u64, String>,
        }

        assert_eq!(*ouroboros_to_rex(&Foo::t()), Foo::to_type());
        assert_eq!(rex_to_ouroboros(&Foo::to_type()), Foo::t());
    }
}
