use ouroboros::alias::Alias;
use ouroboros::field::{Fields, NamedField, NamedFields, UnnamedField, UnnamedFields};
use ouroboros::generic::Generic;
use ouroboros::product::{Array, Func, Record, RecordDocs, RecordFieldDocs, Tuple};
use ouroboros::ptr::Ptr;
use ouroboros::sum::{Enum, EnumVariant, Fallible, Optional, Union, UnionVariant};
use ouroboros::symbolic::Symbolic;
use ouroboros::type_info::Type as OuroborosType;
use rex::{ADT, ADTVariant, AppliedType, EnumPatch, JsonOptions, Type as RexType, TypeCon};
use std::{
    collections::{BTreeMap, HashMap},
    sync::Arc,
};

// Note: We cannot use From/Into here as these only work if the types
// they are implemented on are defined in the same crate

pub fn ouroboros_to_rex(
    our_type: &OuroborosType,
    opts: &JsonOptions,
) -> Result<Arc<RexType>, String> {
    match our_type {
        OuroborosType::Unit => Ok(Arc::new(RexType::Tuple(vec![]))),
        OuroborosType::Bool => Ok(Arc::new(RexType::Con(TypeCon::Bool))),
        OuroborosType::I8 => Ok(Arc::new(RexType::Con(TypeCon::Int))),
        OuroborosType::I16 => Ok(Arc::new(RexType::Con(TypeCon::Int))),
        OuroborosType::I32 => Ok(Arc::new(RexType::Con(TypeCon::Int))),
        OuroborosType::I64 => Ok(Arc::new(RexType::Con(TypeCon::Int))),
        OuroborosType::I128 => Err("Unsupported ouroboros type: I128".to_string()),
        OuroborosType::U8 => Ok(Arc::new(RexType::Con(TypeCon::Uint))),
        OuroborosType::U16 => Ok(Arc::new(RexType::Con(TypeCon::Uint))),
        OuroborosType::U32 => Ok(Arc::new(RexType::Con(TypeCon::Uint))),
        OuroborosType::U64 => Ok(Arc::new(RexType::Con(TypeCon::Uint))),
        OuroborosType::U128 => Err("Unsupported ouroboros type: U128".to_string()),
        OuroborosType::F32 => Ok(Arc::new(RexType::Con(TypeCon::Float))),
        OuroborosType::F64 => Ok(Arc::new(RexType::Con(TypeCon::Float))),
        OuroborosType::String => Ok(Arc::new(RexType::Con(TypeCon::String))),
        OuroborosType::Array(a) => Ok(Arc::new(RexType::App(
            Arc::new(RexType::Con(TypeCon::List)),
            ouroboros_to_rex(&a.t, opts)?,
        ))),
        OuroborosType::Record(r) => {
            let t_docs: Option<BTreeMap<String, String>> = match &r.doc {
                Some(rdocs) => match &rdocs.fields {
                    Some(RecordFieldDocs::Named(named)) => {
                        if !named.is_empty() {
                            Some(BTreeMap::from_iter(named.clone()))
                        } else {
                            None
                        }
                    }
                    Some(RecordFieldDocs::Unnamed(_)) => None,
                    None => None,
                },
                None => None,
            };

            Ok(Arc::new(RexType::ADT(ADT {
                name: r.n.clone(),
                variants: vec![ADTVariant {
                    name: r.n.clone(),
                    t: Some(fields_to_rex(&r.fields, opts)?),
                    docs: None,
                    t_docs,
                    discriminant: None,
                }],
                docs: None, // Not generated by #[derive(TypeInfo)]
            })))
        }
        OuroborosType::Tuple(tuple) => unnamed_fields_to_rex(&tuple.fields, opts),
        OuroborosType::Func(func) => Ok(RexType::arrow(
            ouroboros_to_rex(&func.a, opts)?,
            ouroboros_to_rex(&func.b, opts)?,
        )),
        OuroborosType::Enum(e) => {
            let patches = opts.int_enums.get(&e.n);
            Ok(Arc::new(RexType::ADT(ADT {
                name: e.n.clone(),
                variants: e
                    .variants
                    .iter()
                    .map(|v| ADTVariant {
                        name: v.n.clone(),
                        t: None,
                        docs: None,
                        t_docs: None,
                        discriminant: get_discriminant(v, patches),
                    })
                    .collect::<Vec<_>>(),
                docs: None, // Not generated by #[derive(TypeInfo)]
            })))
        }
        OuroborosType::Fallible(f) => Ok(RexType::result(
            ouroboros_to_rex(&f.err, opts)?,
            ouroboros_to_rex(&f.ok, opts)?,
        )),
        OuroborosType::Optional(o) => Ok(Arc::new(RexType::App(
            Arc::new(RexType::Con(TypeCon::Option)),
            ouroboros_to_rex(&o.t, opts)?,
        ))),
        OuroborosType::Union(u) => {
            let mut variants: Vec<ADTVariant> = Vec::new();
            for v in u.variants.iter() {
                variants.push(ADTVariant {
                    name: v.n.clone(),
                    t: match &v.fields {
                        Some(Fields::Named(fields)) => Some(named_fields_to_rex(fields, opts)?),
                        Some(Fields::Unnamed(fields)) => match fields.fields.len() {
                            0 => None,
                            1 => Some(ouroboros_to_rex(&fields.fields[0].t, opts)?),
                            _ => Some(unnamed_fields_to_rex(fields, opts)?),
                        },
                        None => None,
                    },
                    docs: None,
                    t_docs: None,
                    discriminant: None,
                });
            }

            Ok(Arc::new(RexType::ADT(ADT {
                name: u.n.clone(),
                variants,
                docs: None,
            })))
        }
        OuroborosType::Ptr(ptr) => Ok(Arc::new(RexType::ADT(ADT {
            name: "Ptr".to_string(),
            docs: None,
            variants: vec![ADTVariant {
                name: "Ptr".to_string(),
                t: Some(ouroboros_to_rex(&ptr.t, opts)?),
                docs: None,
                t_docs: None,
                discriminant: None,
            }],
        }))),
        OuroborosType::Symbolic(symbolic) => Ok(Arc::new(RexType::ADT(ADT {
            name: symbolic.n.to_string(),
            docs: symbolic.doc.as_ref().map(|d| d.to_string()),
            variants: vec![ADTVariant {
                name: symbolic.n.clone(),
                t: None,
                docs: None,
                t_docs: None,
                discriminant: None,
            }],
        }))),
        OuroborosType::Generic(g) => Ok(Arc::new(RexType::UnresolvedVar(g.n.clone()))),
        OuroborosType::Alias(alias) => ouroboros_to_rex(&alias.t, opts),
    }
}

fn fields_to_rex(fields: &Fields, opts: &JsonOptions) -> Result<Arc<RexType>, String> {
    match fields {
        Fields::Named(named) => named_fields_to_rex(named, opts),
        Fields::Unnamed(unnamed) => unnamed_fields_to_rex(unnamed, opts),
    }
}

fn named_fields_to_rex(fields: &NamedFields, opts: &JsonOptions) -> Result<Arc<RexType>, String> {
    let mut entries: BTreeMap<String, Arc<RexType>> = BTreeMap::new();
    for field in fields.fields.iter() {
        entries.insert(field.n.clone(), ouroboros_to_rex(&field.t, opts)?);
    }
    Ok(Arc::new(RexType::Dict(entries)))
}

fn unnamed_fields_to_rex(
    fields: &UnnamedFields,
    opts: &JsonOptions,
) -> Result<Arc<RexType>, String> {
    let mut rex_types: Vec<Arc<RexType>> = Vec::new();
    for field in fields.iter() {
        rex_types.push(ouroboros_to_rex(&field.t, opts)?);
    }
    Ok(Arc::new(RexType::Tuple(rex_types)))
}

fn get_discriminant(v: &EnumVariant, patches: Option<&Vec<EnumPatch>>) -> Option<i64> {
    let mut discriminant: Option<i64> = None;

    if let Some(patches) = patches {
        for p in patches.iter() {
            if p.enum_name == v.n {
                discriminant = Some(p.discriminant);
            }
        }
    }

    if discriminant.is_none()
        && let Some(d) = v.v {
            discriminant = Some(d.into());
        }
    discriminant
}

fn rex_to_fields(rex_type: &RexType) -> Result<Fields, String> {
    match rex_type {
        RexType::Tuple(rex_types) => {
            let mut our_fields: Vec<UnnamedField> = Vec::new();
            for t in rex_types.iter() {
                our_fields.push(UnnamedField {
                    t: rex_to_ouroboros(t)?,
                });
            }
            Ok(Fields::Unnamed(UnnamedFields { fields: our_fields }))
        }
        RexType::Dict(entries) => {
            let mut our_fields: Vec<NamedField> = Vec::new();
            for (k, t) in entries.iter() {
                our_fields.push(NamedField {
                    n: k.clone(),
                    t: rex_to_ouroboros(t)?,
                });
            }
            Ok(Fields::Named(NamedFields { fields: our_fields }))
        }
        _ => Ok(Fields::Unnamed(UnnamedFields {
            fields: vec![UnnamedField {
                t: rex_to_ouroboros(rex_type)?,
            }],
        })),
    }
}

pub fn rex_to_ouroboros(rex_type: &RexType) -> Result<OuroborosType, String> {
    match rex_type {
        RexType::UnresolvedVar(name) => Ok(OuroborosType::Generic(Generic::new(name))),
        RexType::Var(_) => Err("Unsupported Rex type: Var".to_string()),
        RexType::ADT(adt) => rex_adt_to_ouroboros(adt),
        RexType::App(_, _) => match rex_type.as_applied_type() {
            Some(AppliedType::Arrow(a, b)) => Ok(OuroborosType::Func(Func {
                a: Box::new(rex_to_ouroboros(a)?),
                b: Box::new(rex_to_ouroboros(b)?),
            })),
            Some(AppliedType::Result(err, ok)) => Ok(OuroborosType::Fallible(Fallible {
                ok: Box::new(rex_to_ouroboros(ok)?),
                err: Box::new(rex_to_ouroboros(err)?),
            })),
            Some(AppliedType::Option(t)) => Ok(OuroborosType::Optional(Optional {
                t: Box::new(rex_to_ouroboros(t)?),
            })),
            Some(AppliedType::Promise(_)) => Err("Unsupported Rex type: Promise".to_string()),
            Some(AppliedType::List(t)) => {
                Ok(OuroborosType::Array(Array::new(rex_to_ouroboros(t)?)))
            }
            None => Err("Unsupported Rex type: Unknown App".to_string()),
        },
        RexType::Dict(_) => Err("Unsupported Rex type: Dict".to_string()),
        RexType::Tuple(ts) => {
            if ts.is_empty() {
                Ok(OuroborosType::Unit)
            } else {
                let mut fields: Vec<UnnamedField> = Vec::new();
                for t in ts.iter() {
                    fields.push(UnnamedField::new(rex_to_ouroboros(t)?));
                }
                Ok(OuroborosType::Tuple(Tuple {
                    fields: UnnamedFields { fields },
                }))
            }
        }
        RexType::Con(TypeCon::Arrow) => Err("Unsupported Rex type: Arrow".to_string()),
        RexType::Con(TypeCon::Result) => Err("Unsupported Rex type: Result".to_string()),
        RexType::Con(TypeCon::Option) => Err("Unsupported Rex type: Option".to_string()),
        RexType::Con(TypeCon::Promise) => Err("Unsupported Rex type: Promise".to_string()),
        RexType::Con(TypeCon::List) => Err("Unsupported Rex type: List".to_string()),
        RexType::Con(TypeCon::Bool) => Ok(OuroborosType::Bool),
        RexType::Con(TypeCon::Uint) => Ok(OuroborosType::U64),
        RexType::Con(TypeCon::Int) => Ok(OuroborosType::I64),
        RexType::Con(TypeCon::Float) => Ok(OuroborosType::F64),
        RexType::Con(TypeCon::String) => Ok(OuroborosType::String),
        RexType::Con(TypeCon::Uuid) => Err("Unsupported Rex type: Uuid".to_string()),
        RexType::Con(TypeCon::DateTime) => Err("Unsupported Rex type: DateTime".to_string()),
    }
}

fn rex_adt_to_ouroboros(adt: &ADT) -> Result<OuroborosType, String> {
    if adt.variants.len() == 1 {
        match adt.variants[0].t.as_deref() {
            // ADT with a single variant whose type is a dict -> Record w/named fields
            Some(RexType::Dict(entries)) => {
                return rex_record_to_ouroboros(&adt.name, &adt.variants[0].t_docs, entries);
            }
            // ADT with a single variant whose type is a tuple -> Record w/unnamed fields
            Some(RexType::Tuple(entries)) => {
                let mut fields: Vec<UnnamedField> = Vec::new();
                for entry in entries.iter() {
                    fields.push(UnnamedField {
                        t: rex_to_ouroboros(entry)?,
                    });
                }
                return Ok(OuroborosType::Record(Record {
                    doc: None,
                    n: adt.name.clone(),
                    fields: Fields::Unnamed(UnnamedFields { fields }),
                }));
            }
            // ADT with a single variant of another type -> Alias
            Some(t) => {
                if adt.name == "Ptr" && adt.variants[0].name == "Ptr" {
                    return Ok(OuroborosType::Ptr(Ptr {
                        t: Box::new(rex_to_ouroboros(t)?),
                    }));
                }

                return Ok(OuroborosType::Alias(Alias {
                    n: adt.name.clone(),
                    t: Box::new(rex_to_ouroboros(t)?),
                }));
            }
            None => {
                if adt.variants[0].name == adt.name {
                    return Ok(OuroborosType::Symbolic(Symbolic {
                        n: adt.name.clone(),
                        doc: adt.docs.clone(),
                    }));
                }
            }
        }
    }

    // ADT where no member carries any data value -> Enum
    if adt.variants.iter().all(|v| v.t.is_none()) {
        return rex_enum_to_ouroboros(&adt.name, &adt.variants);
    }

    // General ADT
    let mut our_variants: Vec<UnionVariant> = Vec::new();
    for rex_variant in adt.variants.iter() {
        let fields: Option<Fields> = match &rex_variant.t {
            Some(rex_fields) => Some(rex_to_fields(rex_fields)?),
            None => None,
        };
        our_variants.push(UnionVariant {
            n: rex_variant.name.clone(),
            fields,
        })
    }
    let union_ = Union {
        doc: None,
        n: adt.name.clone(),
        variants: our_variants,
    };
    Ok(OuroborosType::Union(union_))
}

fn rex_record_to_ouroboros(
    name: &str,
    t_docs: &Option<BTreeMap<String, String>>,
    entries: &BTreeMap<String, Arc<RexType>>,
) -> Result<OuroborosType, String> {
    // Match behaviour of #[derive(TypeInfo)] - use empty hashmap for field docs if
    // there are no actual docs present
    let hm: HashMap<String, String> = match t_docs {
        Some(entries) => HashMap::from_iter(entries.clone()),
        None => HashMap::new(),
    };
    let doc: Option<RecordDocs> = Some(RecordDocs {
        record: None,
        fields: Some(RecordFieldDocs::Named(hm)),
    });

    let mut fields: Vec<NamedField> = Vec::new();
    for (k, v) in entries.iter() {
        fields.push(NamedField {
            n: k.clone(),
            t: rex_to_ouroboros(v)?,
        });
    }

    Ok(OuroborosType::Record(Record {
        doc,
        n: name.to_string(),
        fields: Fields::Named(NamedFields { fields }),
    }))
}

fn rex_enum_to_ouroboros(name: &str, variants: &[ADTVariant]) -> Result<OuroborosType, String> {
    Ok(OuroborosType::Enum(Enum {
        doc: None,
        n: name.to_string(),
        variants: variants
            .iter()
            .map(|v| EnumVariant {
                n: v.name.clone(),
                v: None,
            })
            .collect(),
    }))
}

#[cfg(test)]
#[cfg(test)]
pub mod test {
    #![allow(dead_code)]
    use super::*;
    use ouroboros::{ptr::Ptr as OuroborosPtr, type_info::TypeInfo};
    use ouroboros_proc_macro::*;
    use rex::{Rex, type_system::types::ToType};
    // use rex_type_system::types as rex;

    #[test]
    fn test_unit() {
        assert_eq!(
            *ouroboros_to_rex(&OuroborosType::Unit, &Default::default()).unwrap(),
            RexType::Tuple(vec![])
        );
        assert_eq!(
            rex_to_ouroboros(&RexType::Tuple(vec![])).unwrap(),
            OuroborosType::Unit
        )
    }

    #[test]
    fn test_tuple1() {
        let our_type = OuroborosType::Tuple(Tuple {
            fields: UnnamedFields {
                fields: vec![UnnamedField {
                    t: OuroborosType::U64,
                }],
            },
        });
        let rex_type = ouroboros_to_rex(&our_type, &Default::default()).unwrap();
        assert_eq!(
            *rex_type,
            RexType::Tuple(vec![Arc::new(RexType::Con(TypeCon::Uint))])
        );
        assert_eq!(rex_to_ouroboros(&rex_type).unwrap(), our_type);
    }

    #[test]
    fn test_tuple2() {
        let our_type = OuroborosType::Tuple(Tuple {
            fields: UnnamedFields {
                fields: vec![
                    UnnamedField {
                        t: OuroborosType::U64,
                    },
                    UnnamedField {
                        t: OuroborosType::String,
                    },
                ],
            },
        });
        let rex_type = ouroboros_to_rex(&our_type, &Default::default()).unwrap();
        assert_eq!(
            *rex_type,
            RexType::Tuple(vec![
                Arc::new(RexType::Con(TypeCon::Uint)),
                Arc::new(RexType::Con(TypeCon::String))
            ])
        );
        assert_eq!(rex_to_ouroboros(&rex_type).unwrap(), our_type);
    }

    #[test]
    fn test_record_named() {
        #[derive(Rex, TypeInfo)]
        struct Foo {
            /// First field
            a: u64,
            /// Second field
            b: String,
        }

        assert_eq!(
            *ouroboros_to_rex(&Foo::t(), &Default::default()).unwrap(),
            Foo::to_type()
        );
        assert_eq!(rex_to_ouroboros(&Foo::to_type()).unwrap(), Foo::t())
    }

    #[test]
    fn test_record_unnamed() {
        #[derive(Rex, TypeInfo)]
        pub struct Foo(pub u64, pub String);

        assert_eq!(
            *ouroboros_to_rex(&Foo::t(), &Default::default()).unwrap(),
            Foo::to_type()
        );
        assert_eq!(rex_to_ouroboros(&Foo::to_type()).unwrap(), Foo::t())
    }

    #[test]
    fn test_enum() {
        #[derive(Rex, TypeInfo)]
        enum Foo {
            One,
            Two,
        }

        assert_eq!(
            *ouroboros_to_rex(&Foo::t(), &Default::default()).unwrap(),
            Foo::to_type()
        );
        assert_eq!(rex_to_ouroboros(&Foo::to_type()).unwrap(), Foo::t());
    }

    #[test]
    fn test_enum_int() {
        mod int {
            use ouroboros_proc_macro::*;
            use rex::Rex;

            #[derive(Rex, TypeInfo)]
            pub enum Foo {
                One = 1,
                Two = 2,
                Three = 3,
            }
        }

        mod plain {
            use ouroboros_proc_macro::*;
            use rex::Rex;

            #[derive(Rex, TypeInfo)]
            pub enum Foo {
                One,
                Two,
                Three,
            }
        }

        // Rex's ADTVariant doesn't keep track of the integer values associated with enum
        // variants. So when we convert back to the ouroboros type, we'll get the same result
        // as derive(TypeInfo) would produce if there were no integer values in the enum.
        assert_eq!(
            *ouroboros_to_rex(&int::Foo::t(), &Default::default()).unwrap(),
            int::Foo::to_type()
        );
        assert_eq!(
            rex_to_ouroboros(&int::Foo::to_type()).unwrap(),
            plain::Foo::t()
        );
    }

    #[test]
    fn test_union_single_field() {
        #[derive(Rex, TypeInfo)]
        enum Foo {
            One(u64),
            Two(String),
        }

        assert_eq!(
            *ouroboros_to_rex(&Foo::t(), &Default::default()).unwrap(),
            Foo::to_type()
        );
        assert_eq!(rex_to_ouroboros(&Foo::to_type()).unwrap(), Foo::t());
    }

    #[test]
    fn test_union_multiple_fields() {
        #[derive(Rex, TypeInfo)]
        enum Foo {
            One(u64, bool),
            Two(String, f64),
        }

        assert_eq!(
            *ouroboros_to_rex(&Foo::t(), &Default::default()).unwrap(),
            Foo::to_type()
        );
        assert_eq!(rex_to_ouroboros(&Foo::to_type()).unwrap(), Foo::t());
    }

    #[test]
    fn test_union_mixed() {
        #[derive(Rex, TypeInfo)]
        enum Foo {
            One,
            Two(u64),
            Three(String, f64),
        }

        assert_eq!(
            *ouroboros_to_rex(&Foo::t(), &Default::default()).unwrap(),
            Foo::to_type()
        );
        assert_eq!(rex_to_ouroboros(&Foo::to_type()).unwrap(), Foo::t());
    }

    #[test]
    fn test_union_named() {
        #[derive(Rex, TypeInfo)]
        enum Foo {
            One { a: u64, b: String },
            Two { a: f64, b: bool },
        }

        assert_eq!(
            *ouroboros_to_rex(&Foo::t(), &Default::default()).unwrap(),
            Foo::to_type()
        );
        assert_eq!(rex_to_ouroboros(&Foo::to_type()).unwrap(), Foo::t());
    }

    #[test]
    fn test_numeric_roundtrip() {
        // Rex only supports 64-bit numeric types (Uint, Int, Float). Converting from ouroboros
        // types to rex again will therefore result in only the 64-bit variants being present.
        mod different_sizes {
            use ouroboros_proc_macro::*;
            use rex::Rex;

            #[derive(Rex, TypeInfo)]
            pub struct Foo {
                pub u1: u8,
                pub u2: u16,
                pub u3: u32,
                pub u4: u64,
                pub i1: i8,
                pub i2: i16,
                pub i3: i32,
                pub i4: i64,
                pub f1: f32,
                pub f2: f64,
            }
        }

        mod all_64 {
            use ouroboros_proc_macro::*;
            use rex::Rex;

            #[derive(Rex, TypeInfo)]
            pub struct Foo {
                pub u1: u64,
                pub u2: u64,
                pub u3: u64,
                pub u4: u64,
                pub i1: i64,
                pub i2: i64,
                pub i3: i64,
                pub i4: i64,
                pub f1: f64,
                pub f2: f64,
            }
        }

        assert_eq!(
            rex_to_ouroboros(
                &ouroboros_to_rex(&different_sizes::Foo::t(), &Default::default()).unwrap()
            )
            .unwrap(),
            all_64::Foo::t()
        );

        assert_eq!(
            *ouroboros_to_rex(&different_sizes::Foo::t(), &Default::default()).unwrap(),
            all_64::Foo::to_type()
        );
    }

    #[test]
    fn test_alias() {
        let our_type = OuroborosType::Alias(Alias {
            n: "Foo".to_string(),
            t: Box::new(OuroborosType::U64),
        });

        assert_eq!(
            *ouroboros_to_rex(&our_type, &Default::default()).unwrap(),
            RexType::Con(TypeCon::Uint)
        );
    }

    #[test]
    fn test_symbolic_doc() {
        #[derive(Rex, TypeInfo)]
        /// Test
        pub enum Foo {
            Foo,
        }

        let our_type = OuroborosType::Symbolic(Symbolic {
            n: "Foo".to_string(),
            doc: Some("Test".to_string()),
        });
        let rex_type = Foo::to_type();

        assert_eq!(
            *ouroboros_to_rex(&our_type, &Default::default()).unwrap(),
            rex_type
        );
        assert_eq!(rex_to_ouroboros(&rex_type).unwrap(), our_type);
    }

    #[test]
    fn test_symbolic_nodoc() {
        #[derive(Rex, TypeInfo)]
        pub enum Foo {
            Foo,
        }

        let our_type = OuroborosType::Symbolic(Symbolic {
            n: "Foo".to_string(),
            doc: None,
        });
        let rex_type = Foo::to_type();

        assert_eq!(
            *ouroboros_to_rex(&our_type, &Default::default()).unwrap(),
            rex_type
        );
        assert_eq!(rex_to_ouroboros(&rex_type).unwrap(), our_type);
    }

    #[test]
    fn test_ptr() {
        #[derive(Rex)]
        pub enum Ptr {
            Ptr(String),
        }

        let our_type = OuroborosType::Ptr(OuroborosPtr {
            t: Box::new(OuroborosType::String),
        });
        let rex_type = Ptr::to_type();
        assert_eq!(
            *ouroboros_to_rex(&our_type, &Default::default()).unwrap(),
            rex_type
        );
        assert_eq!(rex_to_ouroboros(&rex_type).unwrap(), our_type);
    }

    #[test]
    fn test_func() {
        let our_type = OuroborosType::Func(Func {
            a: Box::new(OuroborosType::U64),
            b: Box::new(OuroborosType::String),
        });
        let rex_type = RexType::arrow(
            Arc::new(RexType::Con(TypeCon::Uint)),
            Arc::new(RexType::Con(TypeCon::String)),
        );

        assert_eq!(
            ouroboros_to_rex(&our_type, &Default::default()).unwrap(),
            rex_type
        );
        assert_eq!(rex_to_ouroboros(&rex_type).unwrap(), our_type);
    }

    #[test]
    fn test_fallible() {
        #[derive(Rex, TypeInfo)]
        pub struct Foo {
            pub a: Result<u64, String>,
        }

        assert_eq!(
            *ouroboros_to_rex(&Foo::t(), &Default::default()).unwrap(),
            Foo::to_type()
        );
        assert_eq!(rex_to_ouroboros(&Foo::to_type()).unwrap(), Foo::t());
    }

    #[test]
    fn test_generic() {
        let our_generic = OuroborosType::Generic(Generic::new("T"));
        let rex_generic = Arc::new(RexType::UnresolvedVar("T".to_string()));
        assert_eq!(
            ouroboros_to_rex(&our_generic, &Default::default()).unwrap(),
            rex_generic
        );
        assert_eq!(rex_to_ouroboros(&rex_generic).unwrap(), our_generic);
    }
}
